In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
items_df = pd.read_csv("data/olist_order_items_dataset.csv")
orders_df = pd.read_csv("data/olist_orders_dataset.csv")

products_df = pd.read_csv("data/olist_products_dataset.csv")
tans_df= pd.read_csv("data/product_category_name_translation.csv")
reviews_df = pd.read_csv("data/olist_order_reviews_dataset.csv")

In [4]:
df = products_df.merge(tans_df,on="product_category_name",how="left")
df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

In [5]:
df = df.merge( items_df,on="product_id",how="left")
df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,order_id,order_item_id,seller_id,shipping_limit_date,price,freight_value
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery,e17e4f88e31525f7deef66779844ddce,1,5670f4db5b62c43d542e1b2d56b0cf7c,2018-04-30 17:33:54,10.91,7.39
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art,5236307716393b7114b53ee991f36956,1,b561927807645834b59ef0d16ba55a24,2018-02-06 19:11:15,248.00,17.99
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure,01f66e58769f84129811d43eefd187fb,1,7b07b3c7487f0ea825fc6df75abd658b,2018-07-11 21:30:20,79.80,7.82
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby,143d00a4f2dde4e0364ee1821577adb3,1,c510bc1718f0f2961eaa42a23330681a,2018-08-07 09:10:13,112.30,9.54
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares,86cafb8794cb99a9b1b77fc8e48fbbbb,1,0be8ff43f22e456b4e0371b2245e4d01,2018-04-17 01:30:23,37.90,8.29

In [6]:
df = df.merge(orders_df,on="order_id",how="left")
df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,order_id,order_item_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery,e17e4f88e31525f7deef66779844ddce,1,5670f4db5b62c43d542e1b2d56b0cf7c,2018-04-30 17:33:54,10.91,7.39,f8a3e963a310aa58b60a5b1fed5bceb5,delivered,2018-04-24 16:16:53,2018-04-24 19:04:19,2018-04-25 17:01:00,2018-04-27 16:42:17,2018-05-09 00:00:00
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art,5236307716393b7114b53ee991f36956,1,b561927807645834b59ef0d16ba55a24,2018-02-06 19:11:15,248.00,17.99,03fc97548af8f58fefc768d12b546c9c,delivered,2018-01-31 18:55:36,2018-01-31 19:11:15,2018-02-05 22:44:47,2018-02-16 13:27:08,2018-02-22 00:00:00
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure,01f66e58769f84129811d43eefd187fb,1,7b07b3c7487f0ea825fc6df75abd658b,2018-07-11 21:30:20,79.80,7.82,e41819d1c95c12c9ce495b630eab8aee,delivered,2018-07-09 21:18:01,2018-07-09 21:30:20,2018-07-10 11:49:00,2018-07-11 23:24:16,2018-07-18 00:00:00
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby,143d00a4f2dde4e0364ee1821577adb3,1,c510bc1718f0f2961eaa42a23330681a,2018-08-07 09:10:13,112.30,9.54,322162b5ca010c2b059cb5224dd818b1,delivered,2018-08-03 08:55:50,2018-08-03 09:31:42,2018-08-03 11:48:00,2018-08-06 15:14:32,2018-08-08 00:00:00
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares,86cafb8794cb99a9b1b77fc8e48fbbbb,1,0be8ff43f22e456b4e0371b2245e4d01,2018-04-17 01:30:23,37.90,8.29,c11c31965ff02cc1d7132df8edfcbc22,delivered,2018-04-11 01:06:37,2018-04-11 01:30:23,2018-04-12 22:56:27,2018-04-13 22:41:44,2018-04-26 00:00:00

In [7]:
df = df.merge( reviews_df,on="order_id",how="left")
df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,order_id,order_item_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery,e17e4f88e31525f7deef66779844ddce,1,5670f4db5b62c43d542e1b2d56b0cf7c,2018-04-30 17:33:54,10.91,7.39,f8a3e963a310aa58b60a5b1fed5bceb5,delivered,2018-04-24 16:16:53,2018-04-24 19:04:19,2018-04-25 17:01:00,2018-04-27 16:42:17,2018-05-09 00:00:00,d71da8fd8c6e3adef26be965f065b8a1,5.0,Vale a pena,Super adooorei o delineador ele é bem preto e ...,2018-04-28 00:00:00,2018-05-04 00:55:02
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art,5236307716393b7114b53ee991f36956,1,b561927807645834b59ef0d16ba55a24,2018-02-06 19:11:15,248.00,17.99,03fc97548af8f58fefc768d12b546c9c,delivered,2018-01-31 18:55:36,2018-01-31 19:11:15,2018-02-05 22:44:47,2018-02-16 13:27:08,2018-02-22 00:00:00,19866247db89845ef558ef19a6c26fcd,5.0,NaN,Excelente apontador! Em 3 segundos uma ponta p...,2018-02-17 00:00:00,2018-02-18 23:24:14
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure,01f66e58769f84129811d43eefd187fb,1,7b07b3c7487f0ea825fc6df75abd658b,2018-07-11 21:30:20,79.80,7.82,e41819d1c95c12c9ce495b630eab8aee,delivered,2018-07-09 21:18:01,2018-07-09 21:30:20,2018-07-10 11:49:00,2018-07-11 23:24:16,2018-07-18 00:00:00,32921b4e09c9a19d61fe46ce04231b84,5.0,NaN,NaN,2018-07-14 00:00:00,2018-07-16 16:20:04
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby,143d00a4f2dde4e0364ee1821577adb3,1,c510bc1718f0f2961eaa42a23330681a,2018-08-07 09:10:13,112.30,9.54,322162b5ca010c2b059cb5224dd818b1,delivered,2018-08-03 08:55:50,2018-08-03 09:31:42,2018-08-03 11:48:00,2018-08-06 15:14:32,2018-08-08 00:00:00,70949d129965fb1ee32aaccec720a19e,1.0,produto divergente,modelo comprado: travesseiro memoria carinho B...,2018-08-07 00:00:00,2018-08-08 11:53:04
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares,86cafb8794cb99a9b1b77fc8e48fbbbb,1,0be8ff43f22e456b4e0371b2245e4d01,2018-04-17 01:30:23,37.90,8.29,c11c31965ff02cc1d7132df8edfcbc22,delivered,2018-04-11 01:06:37,2018-04-11 01:30:23,2018-04-12 22:56:27,2018-04-13 22:41:44,2018-04-26 00:00:00,74c9c7d0bc153bbbc92e4c1597b8ba55,5.0,NaN,NaN,2018-04-17 00:00:00,2018-04-18 04:29:47

In [8]:
df.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'product_category_name_english', 'order_id', 'order_item_id',
       'seller_id', 'shipping_limit_date', 'price', 'freight_value',
       'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [9]:
final_df = df[
    [
        "product_id",
        "product_category_name",
        "product_category_name_english",
        "review_score",
        "review_comment_title",
        "review_comment_message"
    ]
]

print(final_df.head())
print(final_df.shape)

                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

  product_category_name_english  review_score review_comment_title  \
0                     perfumery           5.0         Vale a pena
1                           art           5.0                  NaN
2                sports_leisure           5.0                  NaN
3                          baby           1.0   produto divergente
4                    housewares           5.0                  NaN

                              review_comment_message
0  Super adooorei o delineador ele é bem preto e ...
1  Excelente apontador! Em 3 segundos uma ponta p...
2                                                NaN
3  modelo comprado: travesseiro memoria carinho B...
4                                                NaN
(113314, 6)

In [10]:
df = final_df.drop_duplicates().dropna()
df.head()

,product_id,product_category_name,product_category_name_english,review_score,review_comment_title,review_comment_message
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery,5.0,Vale a pena,Super adooorei o delineador ele é bem preto e ...
3,cef67bcfe19066a932b7673e239eb23d,bebes,baby,1.0,produto divergente,modelo comprado: travesseiro memoria carinho B...
34,f53103a77d9cf245e579ea37e5ec51f0,cama_mesa_banho,bed_bath_table,5.0,Super Recomendo,Entrega super rápida! \r\n
42,d03bd02af9fff4b98f1c972315e5e9ef,moveis_decoracao,furniture_decor,5.0,Ótimo,Chegou rápido e são lindos!
45,d03bd02af9fff4b98f1c972315e5e9ef,moveis_decoracao,furniture_decor,5.0,Amei,Exatamente como na foto e de otima qualidade.....

In [11]:
df.drop(columns=['product_id','product_category_name'],inplace=True)

In [12]:
df.drop(columns=['review_score'],inplace=True)

In [13]:
df.head()

,product_category_name_english,review_comment_title,review_comment_message
0,perfumery,Vale a pena,Super adooorei o delineador ele é bem preto e ...
3,baby,produto divergente,modelo comprado: travesseiro memoria carinho B...
34,bed_bath_table,Super Recomendo,Entrega super rápida! \r\n
42,furniture_decor,Ótimo,Chegou rápido e são lindos!
45,furniture_decor,Amei,Exatamente como na foto e de otima qualidade.....

In [14]:
df.shape

(10205, 3)

In [15]:
df.drop_duplicates()

,product_category_name_english,review_comment_title,review_comment_message
0,perfumery,Vale a pena,Super adooorei o delineador ele é bem preto e ...
3,baby,produto divergente,modelo comprado: travesseiro memoria carinho B...
34,bed_bath_table,Super Recomendo,Entrega super rápida! \r\n
42,furniture_decor,Ótimo,Chegou rápido e são lindos!
45,furniture_decor,Amei,Exatamente como na foto e de otima qualidade.....
...,...,...,...
113281,furniture_decor,Uma boa loja,Recebi antes do prazo chegou corretamente
113286,furniture_decor,Falta as almofadas,Comprei a capa de sofá que já foi entregue ( q...
113297,furniture_decor,Excelente,Adorei
113302,bed_bath_table,Produto ótimo,"Produto de ótima qualidade, fiquei super feliz..."
113313,bed_bath_table,Ótima,Recomendo !!

In [16]:
df = df.drop_duplicates().reset_index(drop=True)

In [17]:
df['product_category_name_english'].unique()

array(['perfumery', 'baby', 'bed_bath_table', 'furniture_decor',
       'computers_accessories', 'office_furniture', 'electronics', 'toys',
       'cool_stuff', 'sports_leisure', 'watches_gifts', 'health_beauty',
       'home_construction', 'pet_shop', 'consoles_games', 'auto',
       'fashion_bags_accessories', 'telephony', 'housewares',
       'home_appliances', 'construction_tools_safety',
       'construction_tools_construction', 'air_conditioning',
       'garden_tools', 'books_general_interest', 'small_appliances',
       'furniture_living_room', 'signaling_and_security',
       'luggage_accessories', 'industry_commerce_and_business', 'drinks',
       'costruction_tools_garden', 'music', 'food_drink',
       'books_technical', 'home_appliances_2',
       'construction_tools_lights', 'stationery', 'party_supplies',
       'fixed_telephony', 'fashion_childrens_clothes', 'food',
       'costruction_tools_tools', 'fashion_shoes', 'computers',
       'christmas_supplies', 'musical_instruments',
       'small_appliances_home_oven_and_coffee', 'audio', 'books_imported',
       'agro_industry_and_commerce', 'fashion_male_clothing',
       'home_confort', 'market_place',
       'kitchen_dining_laundry_garden_furniture', 'cine_photo',
       'dvds_blu_ray', 'tablets_printing_image', 'art',
       'arts_and_craftmanship', 'fashion_underwear_beach',
       'furniture_bedroom', 'cds_dvds_musicals', 'diapers_and_hygiene',
       'flowers', 'home_comfort_2'], dtype=object)

In [18]:
df.to_csv("data/clean_olist_dataset.csv", index=False)